### ISSUE TITLE
no save my time

### ISSUE THREAD

**Issue by 0xtrzy** [bryanmytko/cubetimes#68]
when i hit space and space again program not save my time to statistics

**Comment by bryanmytko** [comment]
@0xtrzy You have to complete a full session of 12 solved cubes for it to save your times to statistics. A full session consists of an average of 12 solves with your lowest and highest dropped.

My app is based on the old way [JNetCube ](https://sourceforge.net/projects/jnetcube/files/jnetcube/1.0/) worked.

I hope this helps!
