### ISSUE TITLE
Screen wake lock

### ISSUE THREAD

**Issue by bukajsytlos** [bryanmytko/cubetimes#76]
Please, consider using Screen wake lock api to prevent screen dimming/locking for slower cube solvers on mobile devices 😅

**Comment by bryanmytko** [comment]
@bukajsytlos I've added this in https://github.com/bryanmytko/cubetimes/commit/9abab1177615cc0622546fcc0dba99ca686a64b8 but keep in mind, the browser support is quite limited: 
https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API#browser_compatibility
From what I can tell it doesn't work on any iOS browsers including Chrome.

<img width="540" alt="Screen Shot 2022-06-18 at 4 09 53 AM" src="https://user-images.githubusercontent.com/617982/174429018-3827da10-b9ae-4d83-b622-ee6abbb1435d.png">

**Comment by bukajsytlos** [comment]
thanks. I would like to try it, but site looks being down.

**Comment by bukajsytlos** [comment]
ah on githube page description there is `www.` which is not working

**Comment by bryanmytko** [comment]
@bukajsytlos Oh, thanks, I'll have to fix the `www` thing, thanks for the heads up!
